# Maze training config

defaults:
  - arch: trm
  - _self_

hydra:
  output_subdir: null

# Data path
data_paths: ['data/maze-30x30-hard-1k']
data_paths_test: []

evaluators: []

# Hyperparams - Training
global_batch_size: 768

epochs: 60000
eval_interval: 10000
min_eval_interval: 50000  # Start eval after 50k epochs
checkpoint_every_eval: True

lr: 1e-4
lr_min_ratio: 1.0
lr_warmup_steps: 2000

# Standard hyperparameter settings for LM, as used in Llama
beta1: 0.9
beta2: 0.95
weight_decay: 1.0
puzzle_emb_weight_decay: 1.0

# Hyperparams - Puzzle embeddings training
puzzle_emb_lr: 1e-4

seed: 0

ema: True  # use Exponential-Moving-Average
ema_rate: 0.999  # EMA-rate
freeze_weights: False  # If True, freeze weights and only learn the embeddings

